### ISSUE TITLE
Aad, I want to set up my development environment and run existing tests

### ISSUE THREAD

**Issue by Nick9500** [Nick9500/FupaCashStocks#2]
[Priority:1]
[SPS: 3]

As a developer, I want to set up my development environment and run existing tests.

Tasks:
1. Set up dev environment and Android Studio IDE.
2. API 27, Nexus 5X for those using Emulator.
3. Build and install the Ministocks widget.
4. Run existing tests and report results.

**Comment by CristiArde** [comment]
environment up and running since Tuesday Jan 22nd

**Comment by githubRaj** [comment]
All team members have their environments setup ad running since last week.
